task 2
GeekHaven/WebD-APK-Month-22 pull request #208
Opened 2022-01-21 17:52 UTC by Ansh212

Issue: 2

2022-01-23 11:39 UTC, Mudit018 commented
@Ansh212 
Correct the JSON format and provide the live link to website

2022-01-23 11:39 UTC, Mudit018 requested changes
Correct the JSON format and provide the live link to website

2022-01-24 09:31 UTC, Mudit018 requested changes
The message field is not an input field, change it to text-container

2022-01-24 13:08 UTC, aknsal approved these changes

2022-01-24 13:08 UTC, merged